### ISSUE TITLE
Gem doesn't work if spree_frontend isn't installed 

### ISSUE THREAD

**Issue by AhmedAliIbrahim** [spree-contrib/spree_mailchimp_ecommerce#23]
Hello,
Gem doesn't work if spree_frontend isn't not installed

**Comment by damianlegawiec** [comment]
Fixed!

**Comment by ammad-fareed** [comment]
@damianlegawiec, I'm still having an issue if I don't use `spree_frontend`. I'm getting `uninitialized constant Spree::CheckoutController (NameError)` when doing `bundle exec rails g spree_mailchimp_ecommerce:install`. Kindly assist.
